[features]
seeds = false
skip-lint = false
[programs.localnet]
staking_program = "E8XgZGvUxsUk9NWaT9KhVP5gidWXKvrrL4Z7Lb2zUnjf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/asad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
